# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cf9c2014a45fb02bee00f49afd0f8c278d3bca2a1094ab6ba765a8b88f4665d1f9f52d8a03128b799d3b7a8c1f6794c6e43f2ee7558ec46ff0f764b0f812457

test:
  secret_key_base: 64f619dce6274e24fc9a4e57260123a88507bc122426e721171202747aee5bb28a497e14df2b6bcac1f6d498c9b4de46223095171c864df6b184226b5d180ac9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
